# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: default
  demands: agent.os -equals Windows_NT
  # vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs: 
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStaginDirectory)'
    zipAfterPublish: True


- script: dotnet tool install --global dotnet-sonarscanner
  displayName: 'SonarQube 1'
- script: dotnet sonarscanner begin /k:"kboom-terapic" /d:sonar.host.url="http://localhost:9000"  /d:sonar.login="1a0ace25b2e8befdf451f95ebdae6e354c0e57d4"
- script: dotnet build
- script: dotnet sonarscanner end /d:sonar.login="1a0ace25b2e8befdf451f95ebdae6e354c0e57d4"
  displayName: 'SonarQube 4'


- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'

